### ISSUE TITLE
conda forge install of idaes

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#102]

**Comment by adowling2** [comment]
@lbianchi-lbl @ksbeattie I'm teaching a graduate elective (starts in 3 weeks) in which I'd like to use IDAES. Is this something we can get working before then?

**Comment by lbianchi-lbl** [comment]
Hi @adowling2, we recently made progress on this and we were able to successfully build the package with all-Conda dependencies and install it from a dedicated channel. We plan to create a new build of the Conda package ready for internal testing later this week when we cut the release.

In addition to the general IDAES Conda package, more specifically for the purpose of your course, we were thinking that it could be worth to look into having a dedicated Conda `environment.yml` file. This is essentially the Conda version of `requirements.txt`, allowing to create a complete Conda environment from scratch in one shot with `conda env create --file environment.yml`.

In my experience, this is a simple but effective way to manage setups with non-trivial dependencies: since all dependencies are known when the environment is created, there is less room for conflict compared to creating an empty environment and installing individual packages one at the time.
Additionally, if the platforms where the environment will be installed are known and homogeneous enough (e.g. all attendants will be using a Windows machine), it is also possible to create the environment file with "strict" dependencies pinning directly from an existing environment that's known to be working, which would reduce the possibility of conflicts even more.

If this sounds like a workable solution, I'm happy to help with setting this up and testing it before the start of the course.

**Comment by adowling2** [comment]
@ksbeattie @lbianchi-lbl Is this something I can test tomorrow or Monday?

**Comment by lbianchi-lbl** [comment]
Update: as of IDAES 1.9.0, we have a working `idaes-pse` package (see https://idaes-pse.readthedocs.io/en/stable/getting_started/index.html?highlight=Conda#generic-install). Currently, this package is built manually and distributed via a dedicated `IDAES-PSE` channel on Anaconda.org.

The next step for this issue would be to enable the `conda-forge` build so that the `idaes-pse` package is built and hosted directly by `conda-forge` (i.e. without requiring the additional `IDAES-PSE` channel).

**Comment by andrewlee94** [comment]
@lbianchi-lbl @adowling2 Did we ever get this working?

**Comment by lbianchi-lbl** [comment]
I have started the process of adding a `conda-forge` recipe for `idaes-pse`: https://github.com/conda-forge/staged-recipes/pull/28221. I'm not sure how long the review process will take, but I'm adding this to the next release since I think the rest of the process shouldn't require a lot of effort on our side.
