### ISSUE TITLE
Surrogate models with logarithmic terms (ln) do not evaluate properly

### ISSUE THREAD

**Issue by tarnold17** [IDAES/idaes-pse#1058]
I trained a surrogate and obtained the following expression for the model:

![image](https://user-images.githubusercontent.com/26798258/209011394-c88f72fe-632e-47c0-9963-a0db60c11052.png)

The "ln" term in the surrogate is problematic. When attempting to evaluate the surrogate model against input data, the following traceback is obtained:

![image](https://user-images.githubusercontent.com/26798258/209011522-3cfe19e3-5829-4a10-b2b7-35f0025477e4.png)

This surrogate model was trained using alamopy; I am not sure if the same can occur for surrogates trained using PySMO.

**Comment by andrewlee94** [comment]
@tarnold17 Thanks for finding this - the issue is that ALAMO uses `ln` to represent natural logs but Pyomo uses `log`, thus it is unable to parse the expression it receives from ALAMO. We need to add a check in the parsing code to replace the `ln` with a `log` - this is only related to ALAMO and does not affect anything else.
