### ISSUE TITLE
Slow units of measure

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#132]
Units of measure seem to be causing a lot of slowness.  This is going to be a critical issue to things like the dynamic power plant model where the model is large and there are a lot of complex expressions.  An easy place to see this is the controller test here https://github.com/IDAES/idaes-pse/tree/main/idaes/generic_models/control.

The old version without units ran in 25 seconds and about 15 seconds was spending solving so it took roughly 10 seconds to set up the model.  The test in the new framework took 100 seconds solve time was the same. So construing the model takes 7 or 8 times as long with units.

If were don't use ```convert``` in our model expressions and we are careful, we may be able to allow units to be turned off.  Just as a test, I swapped out the pyomo units object class for this dummy and the test again runs in 25 seconds.  I think the answer could be to write some good guidelines for how to write models such that units are optional.  We can't afford much slow down on the large dynamic models.

```python
class PyomoUnitsContainerDummy(object):

    def __init__(self):
        pass

    def __getattr__(self, item):
        setattr(self, item, 1)
        return 1

    def get_units(self, expr):
        return None

    def convert_temp_K_to_C(self, value_in_K):
        return value_in_K - 273.15

    def convert_temp_C_to_K(self, value_in_C):
        return value_in_C + 273.15

    def convert_temp_R_to_F(self, value_in_R):
        return value_in_R - 458.67

    def convert_temp_F_to_R(self, value_in_F):
        return value_in_F + 458.67

    def convert(self, src, to_units=None):
        return src

    def convert_value(self, num_value, from_units=None, to_units=None):
        return num_value
```

**Comment by jghouse88** [comment]
I am seeing noticeably slow tests, I was not sure what the issue was.  When I am setting up a flowsheet block, I should be able to set a boolean flag like `support_units` or something. Also, this allows me to use a prop pack without units support (that I put together for a specific application) to be used with say like the IAPWS with units support. Right now, this throws an error.

**Comment by MAZamarripa** [comment]
Currently, the costing method wont work with prop packs without units support.
I like the boolean flag idea, another way could be something like the pyomo method "strip_bounds"

**Comment by andrewlee94** [comment]
I will note that there are two separate issue here. One is the increase in time it takes to build models with unit conversions in them, which is a definite issue. The second it that the test suite now includes explicit checks of unit consistency which take a while to run - which is not an issue unless it gets out of hand, and won't be seen by most users.

**Comment by andrewlee94** [comment]
@MAZamarripa You will probably disagree, but I at least think that costing of all things absolutely requires unit checking. Most costing method use very specific sets of units - if we don't build unit conversions into the costing methods then they are not general (and would only work with property packages in those units).

Setting units in property packages is fairly simple, so I am fine with telling users to go add units if they want to do costing. It is far better than the alternative of a user failing to understand that costing only work for specific units and then complaining that our models are garbage because they gave the "wrong" answer.

**Comment by eslickj** [comment]
I think most of the unit slowness occurs when you build to model for the first time.  Something analogous to strip bounds probably won't help.  If we go down that path, we'll need a flag that says don't use units from the start.  Of course it we do that we have to assume that all the units are consistent.  Lucky if we decide to do something like that now it's pretty easy since we were already operating that way until very recently.  We we go too far down the unit conversions in expressions path, it may be hard to go back.

One thing we may want to think about though is that even with units off, we probably want to units attached to variables to work, and we may even want to be able to assign units to named expressions.  Then maybe we could set a variable value with units, and display variables in whatever units we want.  That would be really useful even if we don't carry units through all the model expression.
