### ISSUE TITLE
Update idaes-ext version from 3.4.0

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1470]
- The topic of whether the idaes-ext version specified in this repository should be updated from the current 3.4.0 came up today during the dev call
- @jsiirola brought up the point that we might want to use [3.4.2](https://github.com/IDAES/idaes-ext/releases/3.4.2) since the binaries are the same as 3.4.0 (IIRC)
- This issue is mostly for @Robbybp and @mrmundt to chime in and decide when the idaes-ext version should be updated (e.g. for the Aug 2024 release, or a later release, etc)

**Comment by Robbybp** [comment]
I support updating to the 3.4.2 binaries for this release. I'd like to run the idaes-ext tests (IDAES test suite) with these binaries before doing so, but otherwise I'm all for bumping the version. Do you know what the proper order is for testing a new release? Update idaes-ext-3.4.2 to be the latest release (instead of pre-release), then bump the version here, then run the tests on idaes-ext (which just use `idaes get-extensions`). It seems like we should be able to run the idaes-ext tests off a pre-release (by passing a url argument to `idaes get-extensions`?), so I'll look into that. For now, I'm running the tests with 3.4.0 to establish a baseline (see https://github.com/IDAES/idaes-ext/actions).

**Comment by Robbybp** [comment]
Tests don't look any worse than those with 3.4.0, so I say we bump the version.
