### ISSUE TITLE
Property initialization routines ignore solver argument

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#202]
In trying to use the property test harness, @TimBartholomew discovered that the `initialize` method of most (if not all) property packages take a `solver` argument, but promptly ignore this by creating their own solver object using "ipopt".

I believe the correct behavior would for the `solver` option to take either an instance of a Pyomo solver or default to `None`. The `initialize` method should then use the solver provided, or if `None`, use the default solver for IDAES (either through the `get_default_solver` method or via the IDAES config.

**Comment by andrewlee94** [comment]
@eslickj What would you suggest as the best way to create the default solver object? The `get_default_solver` method was originally intended to provide a convenient (and centralized) means of doing that, but with the new use of the IDAES Config we were discussing deprecating that method.

The advantage of the centralized method is it means we can change the default solver by modifying the centralized method rather than needing to update every model in the library.

**Comment by eslickj** [comment]
Sorry, not sure how I missed this.  I think the default solver should be "idaes-ipopt," but of course all the initialization methods should take the solver argument and pass it down to any children initialization methods.  I think making it None is also a solid option, but at this point people probably expect it to just work with Ipopt if they don't say otherwise, so the transition could be rough.

**Comment by andrewlee94** [comment]
@eslickj Actually, the transition is fairly straight forward if we use `get_default_solver`. I am basically working my way throguh all the initialize methods and adding something similar to:

```
if solver is None:
    solverobj = get_default_solver()
else:
    solverobj = SolverFactory(solver)
    solverobj.options = optarg
```

I have most of this in place, and it seems to be working fine so far.

This way, we can easily change the default solver by just updating the `get_default_solver` method, which we can point to `idaes-ipopt` at some point (for the first pass I will stick with the current options just so we don't see changes in output values).

**Comment by eslickj** [comment]
@andrewlee94, I guess "idaes-ipopt" serves the purpose of the default solver.  I just wasn't sure if we wanted to set the tolerance to 1e-6 since it would be a change from the plain ipopt defaults, but if you use the ```get_default_solver()``` method everywhere it's the same thing.  The ma27 option we should drop to avoid making trouble for people that don't have it if we are going to use the default solver outside of just testing.  It's a little confusing having two systems to do approximately the same thing.

Sorry I may have been confused before, but when we originally talked about this I thought ```get_default_solver()``` was just for testing, so I didn't give it much thought.

**Comment by eslickj** [comment]
To expand on this, a bit ```get_default_solver()``` used like this could interfere with what people expect to happen, since it sets the tolerance.  If you set an option for the default config where the tolerance is say 1e-5, the get_default_solver() will come along and change it to 1e-6.  Which means if you want to be able to centrally configure the tolerance, you would need to specify the "ipopt-idaes" solver explicitly.  While that's not hard, it's pretty nuanced behavior, and maybe hard to explain.

**Comment by andrewlee94** [comment]
@eslickj To clarify a bit on my end as well, I fully envision the `get_default_solver` just becoming a wrapper for the default `idaes-ipopt` solver with the options from the config file. This will have the advantage that we have a central method for making any future changes, rather than needing to go modify all models separately.

However, changing the solver options will likely break a number of tests for output values, so for now I am keeping `get_default_solver` as it was. Once we have everything centralized, then we can look at changing the solver and options over to the default config.

**Comment by eslickj** [comment]
@andrewlee94, sounds good.  Thinking about it a bit more, we could used the ```get_default_solver()``` method to let us configure what the default solver is.  I can add a config entry for default solver and we can have ```get_default_solver``` read it.  Then you could just globally set it to like conopt or something.

I guess instead of using the wrapper class for ipopt, we could create a wrapper for SolverFactory that sets default solver options.  Then we could do what ipopt-idaes does for any solver.

**Comment by andrewlee94** [comment]
@eslickj Yep, that is more or less the plan. This way everything will be centralized which will make this a lot easier for users (and us) in the future.

**Comment by eslickj** [comment]
@andrewlee94, do you mind if I modify the ```get_default_solver()``` method or are you actively working on it?  I can make a couple quick changes to the config stuff while I'm thinking about it.  I just want to change that one method, a few minor config things, and add the solver factory wrapper.

**Comment by andrewlee94** [comment]
@eslickj I am not working on it directly right now - I am working through all the models and applying it.
