### ISSUE TITLE
Scaling for costing block

### ISSUE THREAD

**Issue by TimBartholomew** [IDAES/idaes-pse#210]
Scaling was recently added for the pressure changer costing block (and possibly more unit models). The implementation has the `calculate_scaling_factors`  hard coded as using the function in `idaes.core.util.unit_costing`. Instead, it should use whatever module the user provided for the `get_costing` function.

For example my flowsheets that optimize the cost of water treatment processes, now have the following the error:
![image](https://user-images.githubusercontent.com/25497093/107599454-902a1e80-6bee-11eb-93f7-388673bbc047.png)

This error occurs because my module that I use for costing does **not** have a `purchase_cost` variable.

Since different costing modules should be allowed to have different variables and define their own scaling, we should point the `calculate_scaling_factors` to the costing module. I'm not sure the best way to do this, but I really think we should implement costing modules more similarly to property packages in that you provide it to a unit model upon creation.

For example:
```
m.fs.U1 = Unit(default={"property_package": m.fs.properties,
                        "costing_package": m.fs.costing_module})
...
m.fs.U1.get_costing()
```

Rather than our current implementation of tagging a function with the costing module:
```
m.fs.U1.get_costing(module=costing_module)
```

**Comment by andrewlee94** [comment]
There is however a second issue here, which is that we need to standardize and document exactly what variables/attributes are expected of a costing block. This is important later on at the flowsheet level when we want to aggregate costs (e.g. total capital cost) where we expect each unit costing to have certain quantities for aggregation.

**Comment by andrewlee94** [comment]
Also, costing was implemented the way it is because it is completely optional (unlike property packages which are mandatory). Costing was implemented such that it was something that could be added as an after-thought to a model - i.e. you can work on getting the model to build and solve first without costing, and then add it later as a final step once you have got the rest of the flowsheet working.

If costing is added as a config argument, then it becomes something that really should be decided upon upfront (yes, you can change config arguments at any point, but you should never be changing config arguments).

**Comment by ksbeattie** [comment]
Taking this off the release boards, waiting for someone to pick this up.

**Comment by andrewlee94** [comment]
This will become part of the new costing framework when it is implemented.
