### ISSUE TITLE
what's the function of obj.add_properties in the class of PhysicalParameterData.

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#28]
![image](https://user-images.githubusercontent.com/50746074/76932883-e8956500-6926-11ea-9b3a-196d048289c1.png)

Hi, As shown in the figure, when I delete the obj.add_properties, the model can run without any error, so I want to know where the obj.add_properties is used.

**Comment by andrewlee94** [comment]
This section serves two purposes.

1. Its primary use is when you are using "build-on-demand" properties - i.e. where you want the framework to only construct those property calculations you need for a given unit. In these cases, the `method` section is important as it is used to tell the framework what method to call in order to construct a given property. For the case you showed above, it seems to be a simple property package which does not use build-on-demand (note that the `methods` are all `None`), thus this section does not get used for that example.
2. A secondary use is to provide a set of metadata that can be used to index a property package to allow users to search through a library of packages to find those that might suit their needs. This has not been extensively used yet, in part because we have a fairly limited library of packages.

**Comment by andrewlee94** [comment]
@TheHuangs Did this answer your questions about the metadata classes?
