### ISSUE TITLE
How many config do I need to define a controlvolume?

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#30]
Hi,
 I found that there are too many config when build a unit such as flash or PFR reactor.  They share some common config  such as "dynamic","material_balance_type", while they have some unique configs, for example the config block of PFR  reactor has "reaction_package" .

My question is why the the CONFIG block has an attribution of reaction_package when "reaction_package" has not been declared with the method of CONFIG.declare() for the Flash model. and the value of self.config.reaction_package is None.

**Comment by andrewlee94** [comment]
Hi @TheHuangs,

First, you need to make a distinction between the the Config Block and the Control Volume methods.

The Control Volume components are general, and every model uses the same based control volume classes and methods. As such, these methods contain every possible option for building the balance equations. However, you do not need to use all of them in a given model.

The Config Blocks on the other hand are unit model specific. As such, we only include those options that actually matter in the Config Block, so a `Flash` unit does not include reaction packages for example. The options in the Config Block are passed to the Control Volume methods as appropriate, and any undefined options are left blank, or hard coded to an expected value (for example, a `Heater` does not have a heat transfer option, as it will always be `True` - instead the control volume option is hard coded to `True`).

From you original question and our previous discussions, I am guessing you might be looking at the generic Config Block defined in `control_volume_base.py`. This is intended as an example of all the available options so that users are aware of them. However, you should not need to define all of these if you do not need them (the framework should assume that if it is not in the Config Block, or it is None, then an option is not needed).

**Comment by TheHuangs** [comment]
@andrewlee94  thank you.
