### ISSUE TITLE
k_aug available test?

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#327]
I have a problem that cuts across a few projects, so I'll just put it here.  I have k_aug it runs and seems to work.  The problem is that ASL solver "available" method test looks for the version to make sure it's there and runs.  I think the regex stuff that looks for the version in the version string comes up empty making the "available" method return False.  I don't know why this is a problem for me but not the automated tests. This makes the uncertainty propagation not work for me.  After a lot of searching I found this.

```
> k_aug --version
[K_AUG] written by D.T. @2018 (x86_64-w64-mingw32), ASL(20190605)
```

Then ```ASL._extract_version()``` with that string returns None.  At least it seem that way.  I did verify the string is making it to that method, and I'm 99.9% sure that's what's going wrong.

**Comment by adowling2** [comment]
@eslickj Where is `ASL._extract_version()` defined? In IDAES-PSE, Pyomo, or somewhere else?

**Comment by eslickj** [comment]
@adowling2, sorry it's in Pyomo.  The ASL solver plugin.

**Comment by Robbybp** [comment]
Try re-building k_aug from the most up-to-date default branch. Should be fixed as of https://github.com/dthierry/k_aug/pull/55

**Comment by eslickj** [comment]
@Robbybp, looks like you are right.  My build is from 4/20.  I guess this requires building a new set of IDAES binaries.  Do the automated tests not use the k_aug in the idaes binaries?

**Comment by Robbybp** [comment]
Not sure, but they probably use k_aug from the binaries. They are probably using release of Pyomo, however. I believe the requirement to be able to parse the version string is relatively recent in Pyomo. Are you working with a recent branch of Pyomo?

**Comment by jsiirola** [comment]
The assumption that all ASL solvers report a "sane" version number was added pretty recently (https://github.com/Pyomo/pyomo/commit/278151aa0ec57f5c4382d4457fa29039063f1d9e; see also discussion [here](https://github.com/Pyomo/pyomo/pull/1613#discussion_r619500008)).  At the time, the justification for checking was because we were getting "available" solvers because Pyomo could find an executable by the same name -- that wasn't *really* an ASL solver, and I couldn't find an ASL solver that didn't report a version.

**Comment by eslickj** [comment]
I see my k_aug is too old and Pyomo is too new.  I'll put out a new binary release soon, and we should be good.
