### ISSUE TITLE
Can IDAES supports solids?

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#33]
In some case, phase of stream is not only Vap or Liq, but also solid, how to deal with solids in idaes?

**Comment by andrewlee94** [comment]
Hi Bo,

That is a rather open-ended question. The simple answer is you just create a new phase for your solids and write the necessary constraints to describe the properties. For most unit models, there is no special meaning attached to the phase names, and you can use whatever names you want.

The only exception to this is the Flash unit, which requires only two phases named "Liq" and "Vap" as the behaviour is dependent on the phase. The next release of IDAES will improve this by allowing you to specify phase types instead (Liquid, Solid or Vapor) and decide on the behaviour using the type rather than the phase name.

Andrew Lee, PhD
Senior Engineer, KeyLogic Systems

Contractor for the Department of Energy

National Energy Technology Laboratory

626 Cochrans Mill Road, Pittsburgh, PA 15236-0940

andrew.lee@netl.doe.gov | 412.386.7103 (main) | 412.386.5988 (office) |

The information contained in this message may be privileged, private and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message.

________________________________
