### ISSUE TITLE
Fragile model tests

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#344]
In working on addressing #330 and #340, a few tests were discovered that fail under specific circumstances, suggesting an underlying issue that needs to be addressed.

Know tests include:

- PFR tests with saponification properties - outright solver failure. Occurs when running PFR tests in isolation.
- Distiallation (reboiler?) - small deviation from expected value. Have not determined how to reliably reproduce yet.
- Pressure changer - I recall seeing this turn up as well

These failures maybe related to unexpected changes in default solver options during testing.

**Comment by eslickj** [comment]
@andrewlee94, I've seen all those,  I think I mostly sorted them out in PR #323.  I think they are all due to solver config changes.  They only work when you run all the tests, since the default solvers settings change as a side affect of some previous test.  I also fixed a bug (my fault) that caused get_solver not to get the solver right.  That was causing the solver tolerances not to be what was expected.

**Comment by eslickj** [comment]
@andrewlee94, we may be able to close this with the merging of #323, but I wanted to double check with you before I close it.  The tests should no longer interfere with each other.

**Comment by andrewlee94** [comment]
@eslickj I was waiting for #323 to merge so that I could test this properly - I will look at this today and see if the problem has been fixed.
