### ISSUE TITLE
Is there a method to treat zero flow for some species in a flowsheet?

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#35]
I just take an example to illustrate the problem: In a flowsheet, there are nine species for the whole flowsheet, but  there are only five species in the first  unit, that is there are 4 species in the first unit having zero flow. unfortunately, phase equilibrium should be considered in the first unit, which will cause some problem in the activity coefficient properties equations, namely zero flow will cause many numerical problem, such as 1/0, log(0),0^0.5 and so on. is there some good method to deal with this problem?

I have another question. how to initialize properties package,  is there something like m.fs.unit.initialize()

**Comment by andrewlee94** [comment]
There are two approaches to dealing with zero flow and the associated numerical issues. The first is to try to avoid any function that will result in a singularity, e.g. instead of writing x = y/z, you should write x*z = y to avoid the division by zero error (although this can lead to a degenerate problem instead). Secondly, instead of using zero, use an arbitrary small number (we often use 1e-5).

Regarding initialization, all IDAES models are expected to have an initialize() method, whether they are unit models or property packages.

Andrew Lee, PhD
Senior Engineer, KeyLogic Systems

Contractor for the Department of Energy

National Energy Technology Laboratory

626 Cochrans Mill Road, Pittsburgh, PA 15236-0940

andrew.lee@netl.doe.gov | 412.386.7103 (main) | 412.386.5988 (office) |

The information contained in this message may be privileged, private and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message.

________________________________

**Comment by ksbeattie** [comment]
@TheHuangs, would you be willing to post these sort of questions to our "idaes-users" email list rather than creating new issues in github?

It's not a big problem or anything, but I'd like to try and move some of this conversation to where other IDAES users might be helped by these discussions.

If so, send me an email at KSBeattie@lbl.gov and I'll subscribe you.
