### ISSUE TITLE
Installation in Ubuntu

### ISSUE THREAD

**Issue by BobetL** [IDAES/idaes-pse#37]
We tried to install IDAES in Ubuntu 16.04.
These are the commands that we used:

```
# This is in the terminal.
$ mkdir dockerDir
$ cd dockerDir
$ touch Dockerfile
```
```
# This is in the Dockerfile created just now.
FROM Jupyter/datascience-notebook:latest

RUN conda install --quiet -y glpk==4.65 pyomo==5.7 && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

RUN pip install --quiet --no-cache-dir idaes-pse==1.5.1 && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
RUN idaes get-extensions
RUN idaes get-examples
```

```
# This is in the terminal.
$ sudo docker build -t jupyter/test-notebook:latest
```

In the terminal it says successfully installed all of the packages, and also got extensions and examples of idaes.
When we entered JupyterLab, both `import pyomo` and `import idaes` work but there is no examples folder, so we cannot do workshops.
We checked the path with the command `idaes lib-directory` in the terminal of JupyterLab, and entered where it says the files are, but there is still no any files inside the lib folder.

**Comment by ksbeattie** [comment]
Hi @BobetL,

Can you try again with the latest release of idaes-pse?  Just remove the `==1.5.1` and I think it should work.  There was a bug in the `get-examples` command that was fixed after the 1.5.1 release that caused it to not correctly download the extensions properly.

Also, I don't think you actually need the `pyomo==5.7` at the top there as pyomo will get installed by idaes-pse.

Finally, you may want to add ` --platform ubunutu2005` to the `idaes get extensions` command since for some reason it isn't correctly identifying the os and dowloading centos extensions (which probably work, but perhaps not entirely).

**Comment by ksbeattie** [comment]
Update: I just noticed there's a few things missing in that Dockerfile and found a bug in the ubuntu2004 extensions package.  Here's an updated Dockerfile that seems to work better:

```
# This is in the Dockerfile created just now.
FROM jupyter/datascience-notebook:latest

USER root
RUN apt-get -qq update && \
    apt-get -qq -y upgrade && \
    apt-get -qq -y install libgfortran4 libgomp1 liblapack3 libblas3 && \
    apt-get -qq autoremove && apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

USER jovyan
RUN conda install --quiet -y glpk==4.65 pyomo==5.7 && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

RUN pip install --quiet --no-cache-dir idaes-pse && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
RUN idaes get-extensions --platform ubuntu1910
RUN idaes get-examples
```

**Comment by xiangao1** [comment]
@ksbeattie Hi Keith, this is Xian. Last week I was installing IDAES on a Ubuntu 18.04 machine and I also ran into a similar issue. When I use the default `idaes get-extentions` command, it installed centos for me and I could not pass the tests due to IPOPT failures. Then I used `idaes get-extentions --platform ubunutu1804` and it worked.

**Comment by jghouse88** [comment]
@BobetL Did this fix the problem?

**Comment by BobetL** [comment]
It seems that our Ubuntu version is not supported.
We are now confirming if it's ok for our server to upgrade the Ubuntu version.

**Comment by jghouse88** [comment]
@BobetL We are closing this issue now but please get back to us if you have any other questions.
