### ISSUE TITLE
Constraints appearing in Feed and Product blocks

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#471]
At present, Feed blocks can generate constraints [despite the documentation promising that they don't](https://idaes-pse.readthedocs.io/en/stable/technical_specs/model_libraries/generic/unit_models/feed.html?highlight=Feed).

```
from pyomo.environ import ConcreteModel, Constraint
from idaes.core import FlowsheetBlock
from idaes.generic_models.unit_models import Feed

#Import idaes logger to set output levels


m = ConcreteModel()
m.fs = FlowsheetBlock(default={"dynamic": False})

from idaes.generic_models.properties.activity_coeff_models.BTX_activity_coeff_VLE \
    import BTXParameterBlock
    
m.fs.properties = BTXParameterBlock(default={"valid_phase": ('Liq', 'Vap'),
                                            "activity_coeff_model": "Ideal",
                                            "state_vars": "FTPz"})

m.fs.feed = Feed(default={"property_package": m.fs.properties})

for con in m.fs.feed.component_data_objects(ctype=Constraint):
    print(con)
```

> fs.feed.properties[0.0].eq_total
> fs.feed.properties[0.0].eq_comp[benzene]
> fs.feed.properties[0.0].eq_comp[toluene]
> fs.feed.properties[0.0].eq_sum_mol_frac
> fs.feed.properties[0.0]._t1_constraint
> fs.feed.properties[0.0].eq_temperature_bubble
> fs.feed.properties[0.0]._teq_constraint
> fs.feed.properties[0.0].eq_temperature_dew
> fs.feed.properties[0.0].eq_phase_equilibrium[benzene]
> fs.feed.properties[0.0].eq_phase_equilibrium[toluene]
> fs.feed.properties[0.0].eq_P_vap[benzene]
> fs.feed.properties[0.0].eq_P_vap[toluene]

This appears to be a collision between the BTXParameterBlock and Feed/Product blocks. Those process blocks assume that setting `has_phase_equilibrium = False` is sufficient to prevent phase equilibrium constraints from being formed, but the `ActivityCoeffStateBlockData` class overrides `has_phase_equilibrium = False` if both vapor and liquid phases are present:

```  
        if (self.config.has_phase_equilibrium) or \
                (self.config.parameters.config.valid_phase ==
                    ("Liq", "Vap")) or \
                (self.config.parameters.config.valid_phase ==
                    ("Vap", "Liq")):
            if self.config.parameters.config.activity_coeff_model == "NRTL":
                self._make_NRTL_eq()
            if self.config.parameters.config.activity_coeff_model == "Wilson":
                self._make_Wilson_eq()
            self._make_flash_eq()
```

[Based on the documentation](https://idaes-pse.readthedocs.io/en/stable/technical_specs/core/physical_property_class.html) for `has_phase_equilibrium`, I think the Feed/Product blocks are implemented correctly and BTXParameterBlock incorrectly.

**Comment by andrewlee94** [comment]
@dallan-keylogic After thinking a little more I about this I realized that that is expected behavior. There are a few things behind this that I will try to explain, but we can discuss in person next week.

Firstly, a `Feed` block is basically treated in the same way as an inlet to a unit model - we don't have anything in place to realize that this is a special case of a process feed. For the inlet of a general unit model, we need to have the enthalpy of the stream in order to perform the energy balances. However, for the activity coefficient property package (and many of our property packages), the state variables (inlets) are expressed in terms of mixture properties (notably mole fractions are for the overall mixture). As the system is potentially two-phase (and we have no way of knowing a priori), that means we need to do a flash calculation to determine the phase composition in order to get the enthalpy of each phase.

For the inlet to a unit model that all makes sense and is necessary, but for the special case of a feed, we don't really need that (as there is no energy balance, hence no need to calculate enthalpy). However, as we lack any way to tell the property package that this is a feed and not a normal inlet, it has no way of knowing that it doesn't need to do the flash calculation. Hence, even though it is not needed, the flash calculations are constructed for the feed.

So, the question then becomes "is it worth adding some extra way to indicate that a state represents a feed and that there is no need for the flash calculations?". It can be done, and the basic framework it isn't particularly hard either, but implementing the logic in each property package is a bit more work. On the other hand, does having these calculations present actually cause a problem? For that, we lack enough use cases, so I can't give a good answer.

Finally, you noted that the documentation for the Feed block said that it adds no constraints to the model, but you were surprised to see constraints being constructed. The reason for this is that the Feed block itself adds no constraints, but the underlying property package did - i.e. it is a subtle technicality that is not well conveyed. If you can suggest a way to improve the documentation, it would be appreciated.
