### ISSUE TITLE
Installation - pytest fails

### ISSUE THREAD

**Issue by REI-Gardner** [IDAES/idaes-pse#530]
I am on a windows machine and I have installed idaes-pse for the first time. However, when I do the pytest command as specified in the online idaes documentation I get the error message shown below.

I have opened the tutorials and when I do: 
`run "notebook_test_script.py"`
I get that everything passes. 

Is it likely that I will run into any future because of the problem causing the error message from the pytest? Is there a simple fix to resolve the pytest fail?

![idaes error](https://user-images.githubusercontent.com/90857416/135337210-cfda51ce-ba84-4a23-b757-acb6f32c13fc.PNG)

**Comment by lbianchi-lbl** [comment]
Hi @REI-Gardner, the specific error reported in this issue can be fixed by installing the missing `addheader` package by running `pip install addheader` in the same `idaes` Conda environment.

More in general, `pytest` and `addheader` are both considered development dependencies for IDAES. The development dependencies can be installed after cloning this repository from GitHub following the "Installation with GitHub" section of the [Advanced User Installation](https://idaes-pse.readthedocs.io/en/stable/advanced_user_guide/advanced_install/index.html) guide in the IDAES documentation. In summary:

```sh
git clone https://github.com/IDAES/idaes-pse.git && cd idaes-pse
conda activate idaes
pip install -r requirements-dev.txt
pytest
```

**Comment by lbianchi-lbl** [comment]
@REI-Gardner I've just opened #537 so that we can improve this workflow. Let me know if the steps described in my previous comment didn't work, otherwise we can probably close this issue and keep track of this there.
