### ISSUE TITLE
Setting up IDAES on CentOS cluster (Stanford - sherlock) 

### ISSUE THREAD

**Issue by avdudchenko** [IDAES/idaes-pse#612]
Hi, 
I have been trying to set up idaes on a Sherlock cluster ran at Stanford. The use CentOS, with Slurm. 

I can setup IDAES and run ideas get-extensions without errors. However, trying to run a solve leads to following error: 

ERROR: Solver (ipopt) returned non-zero return code (127)
ERROR: Solver log: /home/users/adudchen/.idaes/bin/ipopt: error while loading
    shared libraries: liblapack.so.3: cannot open shared object file: No such file or directory

Upon further inspection of ipopt setup, running ldd libsipopt.so suggests that other libraries are not found,

$ ldd libsipopt.so
        linux-vdso.so.1 =>  (0x00007ffe9f10d000)
        libipopt.so.3 => not found
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f684b291000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f684b055000)
        liblapack.so.3 => not found
        libblas.so.3 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f684ae51000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f684ab49000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f684a847000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f684a479000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f684a263000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f684b7e8000)
 
The cluster does have openblas installed, which contains liblapack.so  libopenblas.so  libblas.so  libopenblas.a libopenblas.so.0 . 
Obviously the ipopt install does not seem to use openblas? Or recognize its existence? Any suggestions on resolving this issue. 

Thank you.

**Comment by lbianchi-lbl** [comment]
@avdudchenko, thanks for reporting this issue. Could you provide more information about the solve run for which the error occurred, e.g. the exact command(s) and/or code snippet that were used following `idaes get-extensions`? This is just an educated guess, but I'm thinking this issue could be related to how the IDAES environment is set up (by default, when `idaes` or any of its submodules is imported within a Python process).

**Comment by avdudchenko** [comment]
I just redid the install to get this info. 
Commands as folows:

(idaes) [user]$ conda create --name idaes

(idaes) [user]$ conda activate idaes

(idaes) [user]$ pip3 install idaes-pse --user

(idaes) [user]$ idaes get-extensions
Getting files...
Done
---------------------------------------------------
IDAES Extensions Build Versions
===================================================
Solvers:  v2.4.4 20210525-1411 centos7
Library:  v2.4.4 20210525-1412 centos7
===================================================


I then use the simple example code you have to test the install  (https://github.com/IDAES/examples-pse/blob/main/src/Tutorials/Basics/notebook_test_script.py) 

And get following result

(idaes) [user]$ python3 test.py
Pyomo Import Checks:        Passed
IDAES Import Checks:        Passed
Solver Availability Check:  Passed
ERROR: Solver (ipopt) returned non-zero return code (127)
ERROR: Solver log: /home/users/adudchen/.idaes/bin/ipopt: error while loading
    shared libraries: liblapack.so.3: cannot open shared object file: No such
    file or directory
Traceback (most recent call last):
  File "test.py", line 69, in <module>
    results = solver.solve(m.fs)
  File "/home/users/adudchen/.local/lib/python3.6/site-packages/pyomo/opt/base/solvers.py", line 596, in solve
    "Solver (%s) did not exit normally" % self.name)
pyomo.common.errors.ApplicationError: Solver (ipopt) did not exit normally


Hope this helps (I have to use pip3 install with --user option as installing in "/usr/local/lib64/python3.6" is forbidden...

**Comment by lbianchi-lbl** [comment]
Hi @avdudchenko, thanks for the follow-up. I have a few questions:

- I see that you're creating and activating a Conda environment, which should result any `pip install`ed modules to be installed in that environment
  - To confirm this, you can run e.g. `which pip` or `python -c "import sys; print(sys.executable)"` after activating the environment
  - Typically this is the path stored in the env variable `$CONDA_PREFIX` rather than in the system paths
  - In other words, you shouldn't need to use `pip3` and/or the `--user` flag (unless for some reason the path at `$CONDA_PREFIX` is not writable to your user)
- Going back to the issue with the libraries, I don't think I have any very specific insight on why this could be happening, so I can just suggest some general checks to try:
  - Is something like e.g. `$LD_LIBRARY_PATH` set in the environment that could be affecting how libraries are found?
  - If, as I understand, this is an HPC machine, are there any additional steps to set up the environment, e.g. `module load <...>`?

**Comment by lbianchi-lbl** [comment]
Hi @avdudchenko, is there any update on this from your side? If not, and/or you feel this issue is not applicable anymore, feel free to close it.

**Comment by ksbeattie** [comment]
@avdudchenko, feel free to re-open this, if it's still a concern for you.
