### ISSUE TITLE
On the use of Docker image

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#7]
about the Docker image on S3

**Comment by ksbeattie** [comment]
I'm adding a comment here to give the illusion that I'm contributing something meaningful.

**Comment by hbeden** [comment]
I find that the image is wrong with the REPOSITORY and TAG，which are <none> when I check the images in docker. This is why I can not run it on my Windows platform. @ksbeattie , would like to tell me how to fix this problem? Thank you.
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              21f93bb8862b        8 weeks ago         4.51GB
hello-world         latest              fce289e99eb9        4 months ago        1.84kB

**Comment by ksbeattie** [comment]
@hbeden, thanks for trying things out.  Where exactly did you get the image that you are working with?

**Comment by hbeden** [comment]
Hi,@ksbeattie, I use "Docker images" command to  show the images, but I have assigned a a new name instead of none for this image, now I have successfully run .py example. Would you like to provide .py examples for heat exchanger and others instead of Jupiter notebook style, the docker can not use Jupiter notebook due to the lack of browser.

**Comment by ksbeattie** [comment]
@hbeden, I think the best approach for you right now would be to not use the docker image but following the minimal install instructions under https://idaes-pse.readthedocs.io/ that way you will be able to run your own browser and notebook.

We will be working to get docker containers working better in future releases.
