### ISSUE TITLE
Failing tests with conda install of IDAES

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#740]
A Watertap user just came to me with an issue about failing tests with a new install of IDAES when using a conda install.

![error_image](https://user-images.githubusercontent.com/16341343/156776434-d96d4ebf-f040-4ec2-b999-7e3c5568669c.png)

If I were to take a guess, it is because `omlt` does not have a conda package available, and thus does not get included in the conda install of IDAES. However, `omlt` is required by some of the tests, and thus the entire test run fails when installing via conda unless the user goes and gets `omlt` manually.

Based on this, I think we need to either:

1. Fix the conda install so that `omlt` is included (which might require an `omlt` conda package).
2. Add conditional imports on `omlt` in the code to avoid the test failures if `omlt` is not present.

**Comment by lbianchi-lbl** [comment]
Thanks @andrewlee94. I've just checked and I can confirm that:

- `omlt` does not have a Conda package (at least not that I can find), and therefore is not among the dependencies for the `idaes-pse` Conda package
- Unlike `tensorflow`, `omlt` is not specified as an `extras_require` `optional` dependency in `setup.py`, and the "import or skip" logic is not applied to it

Assuming that we want to minimize the differences between the pip/PyPI and Conda distributions of IDAES, and since `omlt` seems to be used only for `keras_surrogate` similarly to Tensorflow, I think it's reasonable to move `omlt` to the `optional` dependencies in `setup.py` as well.

I'm using #738 for this, since I think it falls under the "ensure that users can run tests regardless of optional dependencies" umbrella. I've also added a few other changes to make sure that the CI checks match that section of the documentation as closely as possible.
