### ISSUE TITLE
IAPWS - mass basis and update htpx function

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#77]
For the IAPWS property package, it will be useful to have the following:
- [x] mass basis in addition to the existing mol basis (or some functionality that leverages the units framework)
- [X] htpx function currently requires T and P or vapor fraction. It will be useful to extend this to return enthalpy as a function of P,x.

**Comment by eslickj** [comment]
The htpx function should work with P, x now, so we are down to adding a mass-based option.  This would just be an option where state variables are enthalpy is in J/kg and flow is in kg/s.  Otherwise mass basis quantities should exist, but I need to double check all those to be sure nothing is missing.

**Comment by eslickj** [comment]
This is done!
