### ISSUE TITLE
Tutorials for the equilibrium reactor and plug reactor as well as the introduction of developing the customized property packages are wanted

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#9]
As the title mentioned

**Comment by andrewlee94** [comment]
Related to https://github.com/IDAES/idaes-dev/issues/33

**Comment by andrewlee94** [comment]
@TheHuangs Thank you for your comment. We have had a number of people ask for model specific tutorials, and we have started discussing how best to do these. Hopefully we will start working on these soon.

A tutorial on custom property packages needs a bit more work, but we know that we need to do one sooner rather than later.

**Comment by TheHuangs** [comment]
Thanks, hope that the column model and CEOS  property package will come soon, I know that initialization is the most difficult part.

**Comment by jghouse88** [comment]
@TheHuangs Should be available in the next major release.

**Comment by ksbeattie** [comment]
@TheHuangs, unfortunately we won't have time to get to these tutorials until an Oct release.  Sorry for the delay...

**Comment by andrewlee94** [comment]
We should have examples for all core unit models now, and we have recently added some examples for custom property packages as well.
