### ISSUE TITLE
Steps toward partial macOS x64 support

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#918]
- [ ] In `idaes-ext`: See if non-IPOPT solver components can be compiled for macOS x64 (@eslickj , @jsiirola)
- [ ] In `idaes-pse` test suite: Ensure tests are skipped/xfailed if unavailable solver libraries are not found (@lbianchi-lbl)
- [ ] In `idaes-pse` docs: Improve information on which features work and which don't depending on platform (@dangunter , @lbianchi-lbl)
  - Maybe compatibility table: `list(platforms) x list(features)`

**Comment by eslickj** [comment]
For compiling, idaes-ext on macOS x64, the build scripts I have will just build everything without the HSL if it's not there, so we should be able to get a no-HSL build on macOS x64 going on GitHub Actions.  It's a little messy but probably doable.  The build is a bit time consuming though, I don't know if there are resource limitations.  If I can get my hands on a x86 Mac I could do the whole build.

Currently only macOS x86-64 has missing features since we don't have a binary build at all.  If we can get something going on GitHub actions, it just won't have HSL.  On other platforms (as far as I know) everything works.

**Comment by ksbeattie** [comment]
@jsiirola is there any update on this that you are aware of?

**Comment by jsiirola** [comment]
@lbianchi-lbl - No, I think @eslickj is looking into it, but there have been a ton of other things going on this week.

**Comment by andrewlee94** [comment]
A lot of this has been addressed or is being done elsewhere so I am closing this issue.
