### ISSUE TITLE
Grid Integration/PySMO Errors From Pandas Version Update

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#966]
Four hours ago, `pandas` released version 1.5 which broke several tests using DataFrame indexing. We should either resolve the issues, and/or temporarily pin `pandas` to the prior stable version 1.4.4.

**Comment by lbianchi-lbl** [comment]
From a first look, it seems there are two separate sets of issues:

- Errors in PySMO due to use of sets instead of lists for columns (according to [this conversation](https://github.com/pandas-dev/pandas/issues/47215), the support or lack thereof for this in pandas has been unclear in the past): these should be easy to fix on our side
- Errors in code using Egret (through Prescient): these can't be fixed on our side. I've opened grid-parity-exchange/Egret#290 to track this

**Comment by bknueven** [comment]
>  Errors in code using Egret (through Prescient): these can't be fixed on our side. I've opened [TypeError: slice indices must be integers or None or have an __index__ method after updating to pandas 1.5 grid-parity-exchange/Egret#290](https://github.com/grid-parity-exchange/Egret/issues/290) to track this

I just cut a new release of Prescient (2.2), which among other things brings in Egret 0.5.3, which has a fix for pandas 1.5+.
